- .github/workflows/hugo.yml
> Attempt to use hugo extended

- .gitignore
- Makefile
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>
> Easy to use makefile

- content/usage/README.md
Initial commit of usage doc and metal lb instructions
> Steps to use metalb and beginning of usage doc

- static/googleff9d4ab19e7459a0.html
Claim google for search console
> Add Google Claim

- content/docs/_index.md
- content/docs/design/index.md
> Use footnotes

- config.toml
Fixes twitter handle for OGP in headers
> Change twitter handle

- content/docs/community/community.md
Signed-off-by: Sally O'Malley <somalley@redhat.com>
update to add slack invite to `Community` page
/cc @iranzo
> update slack invite

- content/docs/deployment-modes/microshift-containerized.md
@cooktheryan the containerized docs are wrong, this fixes them for now, please merge, thanks
> containerized-docs-typos

- content/docs/deployment-modes/microshift-containerized.md
another quick fix to containerized docs, update image-name and service name
> containerized-docs-fix

- .pre-commit-config.yaml
- assets/js/fastsearch.js
- assets/js/fuse.js
- assets/sass/search.scss
- config.toml
- content/search.md
- layouts/_default/baseof.html
- layouts/_default/index.json
- layouts/_default/search.html
> Add search box

- assets/js/toggle.js
- assets/sass/darkmode.scss
- layouts/_default/baseof.html
- layouts/partials/toggle.html
Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>
Closes #35
> Enable dark mode

- content/docs/user-documentation/how-tos/private-registries.md
Fix secret creation syntax and setting as default
> Fix secret creation and defaulting

- config.toml
Change microshift entry icon for microscope 🔬  ?
> Change icon

- content/docs/community/community.md
- content/docs/developer-documentation/contribute.md
- content/docs/developer-documentation/release-management.md
- content/docs/getting-started/microshift-edge-computing.md
- content/docs/user-documentation/accessing-microshift.md
- content/docs/user-documentation/adding-services.md
- content/docs/user-documentation/configuring.md
- content/docs/user-documentation/deploying-microshift/non-containerized.md
- content/docs/user-documentation/disconnected.md
- content/docs/user-documentation/how-tos/acm-with-microshift.md
- content/docs/user-documentation/how-tos/add-image-registry.md
- content/docs/user-documentation/how-tos/gpu-with-microshift.md
Set WIP documents to be draft to avoid reaching pages with no information on the site
> Set current WIP to be drafts

- assets/sass/darkmode.scss
Fixes 'read docs' button when in darkmode and admonition style selector
> Fix dark mode style

- content/docs/user-documentation/how-tos/private-registries.md
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Closes #49
> Fix command pull secret docs

- .yaspeller.json
- CONTRIBUTING.md
- README.md
- content/docs/user-documentation/deploying-microshift/non-containerized.md
Minor updates and rewrite of CONTRIBUTING to reference how to contribute to documentation.
Closes #47
> Fix README, CONTRIBUTING, and typo in rpm install

- content/docs/user-documentation/deploying-microshift/containerized.md
Signed-off-by: Sally O'Malley <somalley@redhat.com>
> remove unnecessary warning

- Makefile
Signed-off-by: Miguel Angel Ajo Pelayo <miguelangel@ajo.es>
> Update to latest hugo

- .github/workflows/hugo.yml
- Makefile
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>
> Use the makefile builder and fix version number

- content/en/docs/getting-started/_index.md
Missing podman install which causes containerized to fail
> inclusion of oc client and podman install

- content/en/docs/user-documentation/how-tos/acm-with-microshift.md
closes #38  and https://github.com/redhat-et/microshift/issues/440
> closes #38

- content/en/docs/getting-started/_index.md
> Add getting started on CentOS and RHEL

- content/en/docs/getting-started/_index.md
> Add AIO section

- content/en/docs/user-documentation/manifests.md
> Add auto-manifest section

- content/en/docs/getting-started/_index.md
`crio` package name should be `cri-o`
> crio package typo

- content/en/docs/getting-started/_index.md
> Small fixes

- README.md
- themes/docsy/README.md
- themes/docsy/userguide/content/en/docs/Getting started/_index.md
> Changes 'sudo npm install' to 'npm install'

- content/en/docs/developer-documentation/build-install-container.md
- content/en/docs/developer-documentation/build-install-rpm.md
- content/en/docs/developer-documentation/local-development.md
> Update and structure dev docs

- content/en/docs/developer-documentation/build-install-container.md
- content/en/docs/user-documentation/manifests.md
> fixing of broken links

- content/en/docs/developer-documentation/build-install-rpm.md
- content/en/docs/developer-documentation/local-development.md
> resolves #97

- content/en/docs/developer-documentation/build-install-rpm.md
Assume use from a non-privileged user account and be consistent about using/not using sudo accordingly.
> Use sudo consistently

- content/en/docs/getting-started/_index.md
> Doc typo fix on MacOS Getting Started

- content/en/docs/getting-started/_index.md
Add missing sudo to allow writing to /etc/yum.repos.d
> Add sudo to curl command

- content/en/docs/getting-started/_index.md
We need to define how to get the arm client.
> Arm client

- content/en/docs/user-documentation/how-tos/acm-with-microshift.md
Signed-off-by: karmab <karimboumedhel@gmail.com>
ACM Documentation
> Update ACM instructions

- content/en/docs/getting-started/_index.md
- content/en/docs/home/_index.md
- content/en/docs/user-documentation/networking/_index.md
- content/en/docs/user-documentation/networking/cni.md
- content/en/docs/user-documentation/networking/exposing-services.md
- content/en/docs/user-documentation/networking/firewall.md
- content/en/docs/user-documentation/networking/mdns.md
- content/en/docs/user-documentation/networking/overview.md
Add networking related documentation.
> Networking documentation

- content/en/docs/user-documentation/how-tos/add-app-images.md
Signed-off-by: Parul <parsingh@redhat.com>
How to on 
`To add application images to container store for  microshift to access on limited or no network build rpm using microshift-app-images.spec`
> Docs on how to build rpm with application images in container store.

- content/en/docs/getting-started/_index.md
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Closes [#631](https://github.com/redhat-et/microshift/issues/631)
> Add OSTree based deployments

- content/en/docs/user-documentation/how-tos/dynamic-pv.md
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Closes: #149
> Add HowTo about dynamic provisioning of PVs

- content/en/docs/getting-started/_index.md
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Closes #[microshift](https://github.com/redhat-et/microshift/issues/658)
> Comment to pause AIO container

- content/en/docs/user-documentation/manifests.md
This commit documents the behaviour implemented in
https://github.com/redhat-et/microshift/pull/659
> Document multiple manifest locations

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- config.toml
- content/en/docs/developer-documentation/build-install-container.md
- content/en/docs/developer-documentation/build-install-rpm.md
- content/en/docs/developer-documentation/local-development.md
- content/en/docs/openshift-portability/_index.md
- content/en/docs/release-notes/_index.md
- content/en/docs/user-documentation/configuring.md
- content/en/docs/user-documentation/how-tos/offline-containers.md
- content/en/docs/user-documentation/manifests.md
- content/en/docs/user-documentation/troubleshooting.md
> replace redhat-et/microshift -> openshift/microshift

- content/en/docs/user-documentation/networking/overview.md
Closes #178 
This PR fixes all of the broken links on the Networking Overview page.
> [DOCS] Fix broken links networking overview

- Makefile
- README.md
- content/en/_index.html
- layouts/partials/navbar.html
- package-lock.json
Also update npm dependencies and simplify Makefile rules.
Closes [USHIFT-6150](https://issues.redhat.com/browse/USHIFT-6150)
> Update getting started and doc redirects to point to microshift-io
